#!/bin/sh
# Setting up Gnome to use Xmonad
touch  /usr/share/applications/xmonad.desktop
#[Desktop Entry]
#Type=Application
#Encoding=UTF-8
#Name=Xmonad
#Exec=xmonad
#NoDisplay=true
#X-GNOME-WMName=Xmonad
#X-GNOME-Autostart-Phase=WindowManager
#X-GNOME-Provides=windowmanager
#X-GNOME-Autostart-Notify=false
nano  /usr/share/applications/xmonad.desktop
nano  /usr/share/xsessions/xmonad.desktop 
#[Desktop Entry]
#Encoding=UTF-8
#Name=XMonad
#Comment=Lightweight tiling window manager
#Exec=xmonad
#Icon=xmonad.png
#Type=XSession
